const CURRENCIES = [
  { code: "ETB", name: "Ethiopian Birr", flag: "🇪🇹", rate: 124.5 },
  { code: "USD", name: "US Dollar", flag: "🇺🇸", rate: 1 },
  { code: "EUR", name: "Euro", flag: "🇪🇺", rate: 0.92 },
  { code: "GBP", name: "British Pound", flag: "🇬🇧", rate: 0.79 },
  { code: "NGN", name: "Nigerian Naira", flag: "🇳🇬", rate: 1530 },
  { code: "KES", name: "Kenyan Shilling", flag: "🇰🇪", rate: 129 },
  { code: "GHS", name: "Ghanaian Cedi", flag: "🇬🇭", rate: 15.2 },
  { code: "ZAR", name: "South African Rand", flag: "🇿🇦", rate: 18.4 },
  { code: "EGP", name: "Egyptian Pound", flag: "🇪🇬", rate: 48.9 },
  { code: "TZS", name: "Tanzanian Shilling", flag: "🇹🇿", rate: 2580 },
  { code: "UGX", name: "Ugandan Shilling", flag: "🇺🇬", rate: 3720 },
  { code: "MAD", name: "Moroccan Dirham", flag: "🇲🇦", rate: 9.9 },
  { code: "XOF", name: "West African CFA", flag: "🇸🇳", rate: 605 },
  { code: "AED", name: "UAE Dirham", flag: "🇦🇪", rate: 3.67 },
  { code: "SAR", name: "Saudi Riyal", flag: "🇸🇦", rate: 3.75 },
  { code: "QAR", name: "Qatari Riyal", flag: "🇶🇦", rate: 3.64 },
  { code: "KWD", name: "Kuwaiti Dinar", flag: "🇰🇼", rate: 0.31 },
  { code: "BHD", name: "Bahraini Dinar", flag: "🇧🇭", rate: 0.38 },
  { code: "OMR", name: "Omani Rial", flag: "🇴🇲", rate: 0.385 },
  { code: "JOD", name: "Jordanian Dinar", flag: "🇯🇴", rate: 0.71 },
  { code: "IQD", name: "Iraqi Dinar", flag: "🇮🇶", rate: 1310 },
  { code: "CHF", name: "Swiss Franc", flag: "🇨🇭", rate: 0.88 },
  { code: "SEK", name: "Swedish Krona", flag: "🇸🇪", rate: 10.6 },
  { code: "NOK", name: "Norwegian Krone", flag: "🇳🇴", rate: 10.8 },
  { code: "PLN", name: "Polish Zloty", flag: "🇵🇱", rate: 3.95 },
  { code: "CZK", name: "Czech Koruna", flag: "🇨🇿", rate: 23.5 },
  { code: "HUF", name: "Hungarian Forint", flag: "🇭🇺", rate: 358 },
  { code: "CNY", name: "Chinese Yuan", flag: "🇨🇳", rate: 7.24 },
  { code: "JPY", name: "Japanese Yen", flag: "🇯🇵", rate: 149.8 },
  { code: "INR", name: "Indian Rupee", flag: "🇮🇳", rate: 83.4 },
  { code: "PKR", name: "Pakistani Rupee", flag: "🇵🇰", rate: 278 },
  { code: "BDT", name: "Bangladeshi Taka", flag: "🇧🇩", rate: 119 },
  { code: "PHP", name: "Philippine Peso", flag: "🇵🇭", rate: 56.8 },
  { code: "VND", name: "Vietnamese Dong", flag: "🇻🇳", rate: 24650 },
  { code: "THB", name: "Thai Baht", flag: "🇹🇭", rate: 35.6 },
  { code: "MYR", name: "Malaysian Ringgit", flag: "🇲🇾", rate: 4.7 },
  { code: "IDR", name: "Indonesian Rupiah", flag: "🇮🇩", rate: 15750 },
  { code: "BRL", name: "Brazilian Real", flag: "🇧🇷", rate: 5.02 },
  { code: "MXN", name: "Mexican Peso", flag: "🇲🇽", rate: 17.1 },
  { code: "ARS", name: "Argentine Peso", flag: "🇦🇷", rate: 920 },
  { code: "COP", name: "Colombian Peso", flag: "🇨🇴", rate: 3950 },
];

// Payment methods per currency
const PAYMENT_METHODS = {
  ETB: ["CBE", "Telebirr"],
  USD: ["Bank Transfer", "Zelle", "PayPal"],
  EUR: ["SEPA Transfer", "Revolut", "Wise"],
  GBP: ["Bank Transfer", "Faster Payments", "Revolut"],
  NGN: ["Bank Transfer", "Opay", "PalmPay"],
  KES: ["M-Pesa", "Bank Transfer"],
  GHS: ["MTN MoMo", "Bank Transfer"],
  ZAR: ["Bank Transfer", "Capitec"],
  EGP: ["Vodafone Cash", "Bank Transfer"],
  TZS: ["M-Pesa", "Tigo Pesa"],
  UGX: ["MTN MoMo", "Airtel Money"],
  MAD: ["Bank Transfer", "CIH Mobile"],
  XOF: ["Orange Money", "Wave"],
  AED: ["Bank Transfer", "Wise"],
  SAR: ["Bank Transfer", "STC Pay"],
  QAR: ["Bank Transfer", "QPay"],
  KWD: ["Bank Transfer", "KNET"],
  BHD: ["Bank Transfer", "BenefitPay"],
  OMR: ["Bank Transfer"],
  JOD: ["Bank Transfer", "CliQ"],
  IQD: ["Bank Transfer", "Zain Cash"],
  CHF: ["Bank Transfer", "Twint"],
  SEK: ["Bank Transfer", "Swish"],
  NOK: ["Bank Transfer", "Vipps"],
  PLN: ["Bank Transfer", "BLIK"],
  CZK: ["Bank Transfer"],
  HUF: ["Bank Transfer"],
  CNY: ["Alipay", "WeChat Pay"],
  JPY: ["Bank Transfer", "PayPay"],
  INR: ["UPI", "Bank Transfer"],
  PKR: ["EasyPaisa", "JazzCash"],
  BDT: ["bKash", "Nagad"],
  PHP: ["GCash", "Bank Transfer"],
  VND: ["Bank Transfer", "Momo"],
  THB: ["Bank Transfer", "PromptPay"],
  MYR: ["Bank Transfer", "Touch n Go"],
  IDR: ["Bank Transfer", "OVO", "Dana"],
  BRL: ["PIX", "Bank Transfer"],
  MXN: ["Bank Transfer", "SPEI"],
  ARS: ["Bank Transfer", "Mercado Pago"],
  COP: ["Bank Transfer", "Nequi"],
};

// Crypto base prices in USD (will be updated live)
const CRYPTO_PRICES = {
  BTC: 67500,
  USDT: 1,
};
