const CRYPTO_LIST = [
  { symbol: "BTC", name: "Bitcoin", icon: "₿", color: "#F7931A" },
  { symbol: "ETH", name: "Ethereum", icon: "Ξ", color: "#627EEA" },
  { symbol: "USDT", name: "Tether", icon: "₮", color: "#26A17B" },
  { symbol: "USDC", name: "USD Coin", icon: "$", color: "#2775CA" },
  { symbol: "BNB", name: "BNB", icon: "B", color: "#F3BA2F" },
  { symbol: "SOL", name: "Solana", icon: "S", color: "#9945FF" },
  { symbol: "XRP", name: "Ripple", icon: "X", color: "#346AA9" },
  { symbol: "ADA", name: "Cardano", icon: "A", color: "#0033AD" },
  { symbol: "DOGE", name: "Dogecoin", icon: "D", color: "#C2A633" },
  { symbol: "TRX", name: "TRON", icon: "T", color: "#EF0027" },
  { symbol: "TON", name: "Toncoin", icon: "💎", color: "#0088CC" },
  { symbol: "MATIC", name: "Polygon", icon: "M", color: "#8247E5" },
  { symbol: "LTC", name: "Litecoin", icon: "L", color: "#BFBBBB" },
  { symbol: "AVAX", name: "Avalanche", icon: "A", color: "#E84142" },
  { symbol: "DOT", name: "Polkadot", icon: "●", color: "#E6007A" },
  { symbol: "LINK", name: "Chainlink", icon: "⬡", color: "#2A5ADA" },
  { symbol: "ATOM", name: "Cosmos", icon: "⚛", color: "#2E3148" },
  { symbol: "UNI", name: "Uniswap", icon: "🦄", color: "#FF007A" },
  { symbol: "XLM", name: "Stellar", icon: "*", color: "#7D00FF" },
  { symbol: "BCH", name: "Bitcoin Cash", icon: "B", color: "#8DC351" },
  { symbol: "ETC", name: "Ethereum Classic", icon: "Ξ", color: "#328332" },
  { symbol: "FIL", name: "Filecoin", icon: "F", color: "#0090FF" },
  { symbol: "APT", name: "Aptos", icon: "A", color: "#1ECBAD" },
  { symbol: "ARB", name: "Arbitrum", icon: "A", color: "#28A0F0" },
  { symbol: "OP", name: "Optimism", icon: "O", color: "#FF0420" },
  { symbol: "NEAR", name: "NEAR Protocol", icon: "N", color: "#00C08B" },
  { symbol: "INJ", name: "Injective", icon: "I", color: "#00A3FF" },
  { symbol: "SUI", name: "Sui", icon: "S", color: "#4DA2FF" },
  { symbol: "SEI", name: "Sei", icon: "S", color: "#9B2FFF" },
  { symbol: "FTM", name: "Fantom", icon: "F", color: "#1969FF" },
  { symbol: "ALGO", name: "Algorand", icon: "A", color: "#000000" },
  { symbol: "HBAR", name: "Hedera", icon: "H", color: "#222222" },
  { symbol: "VET", name: "VeChain", icon: "V", color: "#15BDFF" },
  { symbol: "EGLD", name: "MultiversX", icon: "X", color: "#23F7DD" },
  { symbol: "XMR", name: "Monero", icon: "M", color: "#FF6600" },
];

const DEPOSIT_NETWORKS = {
  BTC: [
    {
      key: "BTC",
      name: "Bitcoin Network",
      fee: "Network fee",
      time: "~30 min",
      confirms: "1 Confirmation",
    },
  ],
  ETH: [
    {
      key: "ERC20",
      name: "Ethereum (ERC20)",
      fee: "High fee",
      time: "~5 min",
      confirms: "12 Confirmations",
    },
    {
      key: "BEP20",
      name: "BNB Smart Chain",
      fee: "Low fee",
      time: "~2 min",
      confirms: "15 Confirmations",
    },
  ],
  USDT: [
    {
      key: "TRC20",
      name: "TRON (TRC20)",
      fee: "Low fee",
      time: "~1 min",
      confirms: "1 Confirmation",
    },
    {
      key: "ERC20",
      name: "Ethereum (ERC20)",
      fee: "High fee",
      time: "~5 min",
      confirms: "12 Confirmations",
    },
    {
      key: "BEP20",
      name: "BNB Smart Chain",
      fee: "Low fee",
      time: "~2 min",
      confirms: "15 Confirmations",
    },
    {
      key: "SOL",
      name: "Solana",
      fee: "Very low",
      time: "~30 sec",
      confirms: "1 Confirmation",
    },
    {
      key: "ARB",
      name: "Arbitrum (ARB)",
      fee: "Low fee",
      time: "~1 min",
      confirms: "1 Confirmation",
    },
    {
      key: "OP",
      name: "Optimism (OP)",
      fee: "Low fee",
      time: "~1 min",
      confirms: "1 Confirmation",
    },
    {
      key: "TON",
      name: "TON Network",
      fee: "Very low",
      time: "~30 sec",
      confirms: "1 Confirmation",
    },
  ],
  USDC: [
    {
      key: "ERC20",
      name: "Ethereum (ERC20)",
      fee: "High fee",
      time: "~5 min",
      confirms: "12 Confirmations",
    },
    {
      key: "BEP20",
      name: "BNB Smart Chain",
      fee: "Low fee",
      time: "~2 min",
      confirms: "15 Confirmations",
    },
    {
      key: "SOL",
      name: "Solana",
      fee: "Very low",
      time: "~30 sec",
      confirms: "1 Confirmation",
    },
    {
      key: "ARB",
      name: "Arbitrum",
      fee: "Low fee",
      time: "~1 min",
      confirms: "1 Confirmation",
    },
  ],
  BNB: [
    {
      key: "BEP20",
      name: "BNB Smart Chain",
      fee: "Low fee",
      time: "~2 min",
      confirms: "15 Confirmations",
    },
  ],
  SOL: [
    {
      key: "SOL",
      name: "Solana Network",
      fee: "Very low",
      time: "~30 sec",
      confirms: "1 Confirmation",
    },
  ],
  XRP: [
    {
      key: "XRP",
      name: "XRP Ledger",
      fee: "Very low",
      time: "~4 sec",
      confirms: "1 Confirmation",
    },
  ],
  ADA: [
    {
      key: "ADA",
      name: "Cardano Network",
      fee: "Low fee",
      time: "~5 min",
      confirms: "15 Confirmations",
    },
  ],
  DOGE: [
    {
      key: "DOGE",
      name: "Dogecoin Network",
      fee: "Low fee",
      time: "~5 min",
      confirms: "6 Confirmations",
    },
  ],
  TRX: [
    {
      key: "TRC20",
      name: "TRON Network",
      fee: "Very low",
      time: "~1 min",
      confirms: "1 Confirmation",
    },
  ],
  TON: [
    {
      key: "TON",
      name: "TON Network",
      fee: "Very low",
      time: "~30 sec",
      confirms: "1 Confirmation",
    },
  ],
  MATIC: [
    {
      key: "MATIC",
      name: "Polygon Network",
      fee: "Very low",
      time: "~2 min",
      confirms: "256 Confirmations",
    },
    {
      key: "ERC20",
      name: "Ethereum (ERC20)",
      fee: "High fee",
      time: "~5 min",
      confirms: "12 Confirmations",
    },
  ],
  LTC: [
    {
      key: "LTC",
      name: "Litecoin Network",
      fee: "Low fee",
      time: "~10 min",
      confirms: "6 Confirmations",
    },
  ],
  AVAX: [
    {
      key: "AVAX-C",
      name: "Avalanche C-Chain",
      fee: "Low fee",
      time: "~2 min",
      confirms: "1 Confirmation",
    },
    {
      key: "BEP20",
      name: "BNB Smart Chain",
      fee: "Low fee",
      time: "~2 min",
      confirms: "15 Confirmations",
    },
  ],
  DOT: [
    {
      key: "DOT",
      name: "Polkadot Network",
      fee: "Low fee",
      time: "~1 min",
      confirms: "1 Confirmation",
    },
  ],
  LINK: [
    {
      key: "ERC20",
      name: "Ethereum (ERC20)",
      fee: "High fee",
      time: "~5 min",
      confirms: "12 Confirmations",
    },
    {
      key: "BEP20",
      name: "BNB Smart Chain",
      fee: "Low fee",
      time: "~2 min",
      confirms: "15 Confirmations",
    },
  ],
  ATOM: [
    {
      key: "ATOM",
      name: "Cosmos Network",
      fee: "Low fee",
      time: "~1 min",
      confirms: "1 Confirmation",
    },
  ],
  UNI: [
    {
      key: "ERC20",
      name: "Ethereum (ERC20)",
      fee: "High fee",
      time: "~5 min",
      confirms: "12 Confirmations",
    },
  ],
  XLM: [
    {
      key: "XLM",
      name: "Stellar Network",
      fee: "Very low",
      time: "~5 sec",
      confirms: "1 Confirmation",
    },
  ],
  BCH: [
    {
      key: "BCH",
      name: "Bitcoin Cash",
      fee: "Low fee",
      time: "~10 min",
      confirms: "6 Confirmations",
    },
  ],
  ETC: [
    {
      key: "ETC",
      name: "Ethereum Classic",
      fee: "Low fee",
      time: "~5 min",
      confirms: "12 Confirmations",
    },
  ],
  FIL: [
    {
      key: "FIL",
      name: "Filecoin Network",
      fee: "Low fee",
      time: "~1 min",
      confirms: "1 Confirmation",
    },
  ],
  APT: [
    {
      key: "APT",
      name: "Aptos Network",
      fee: "Very low",
      time: "~30 sec",
      confirms: "1 Confirmation",
    },
  ],
  ARB: [
    {
      key: "ARB",
      name: "Arbitrum One",
      fee: "Very low",
      time: "~1 min",
      confirms: "1 Confirmation",
    },
  ],
  OP: [
    {
      key: "OP",
      name: "Optimism Network",
      fee: "Very low",
      time: "~1 min",
      confirms: "1 Confirmation",
    },
  ],
  NEAR: [
    {
      key: "NEAR",
      name: "NEAR Network",
      fee: "Very low",
      time: "~2 sec",
      confirms: "1 Confirmation",
    },
  ],
  INJ: [
    {
      key: "INJ",
      name: "Injective Network",
      fee: "Very low",
      time: "~1 min",
      confirms: "1 Confirmation",
    },
  ],
  SUI: [
    {
      key: "SUI",
      name: "Sui Network",
      fee: "Very low",
      time: "~30 sec",
      confirms: "1 Confirmation",
    },
  ],
  SEI: [
    {
      key: "SEI",
      name: "Sei Network",
      fee: "Very low",
      time: "~1 min",
      confirms: "1 Confirmation",
    },
  ],
  FTM: [
    {
      key: "FTM",
      name: "Fantom Opera",
      fee: "Very low",
      time: "~1 min",
      confirms: "1 Confirmation",
    },
  ],
  ALGO: [
    {
      key: "ALGO",
      name: "Algorand Network",
      fee: "Very low",
      time: "~5 sec",
      confirms: "1 Confirmation",
    },
  ],
  HBAR: [
    {
      key: "HBAR",
      name: "Hedera Network",
      fee: "Very low",
      time: "~5 sec",
      confirms: "1 Confirmation",
    },
  ],
  VET: [
    {
      key: "VET",
      name: "VeChain Network",
      fee: "Very low",
      time: "~1 min",
      confirms: "1 Confirmation",
    },
  ],
  EGLD: [
    {
      key: "EGLD",
      name: "MultiversX Network",
      fee: "Very low",
      time: "~1 min",
      confirms: "1 Confirmation",
    },
  ],
  XMR: [
    {
      key: "XMR",
      name: "Monero Network",
      fee: "Low fee",
      time: "~20 min",
      confirms: "10 Confirmations",
    },
  ],
};

// ⚠️ EDIT THESE WITH YOUR REAL ADDRESSES
const DEPOSIT_ADDRESSES = {
  BTC: { BTC: "YOUR_BTC_ADDRESS" },
  ETH: { ERC20: "YOUR_ETH_ERC20_ADDRESS", BEP20: "YOUR_ETH_BEP20_ADDRESS" },
  USDT: {
    TRC20: "YOUR_USDT_TRC20_ADDRESS",
    ERC20: "YOUR_USDT_ERC20_ADDRESS",
    BEP20: "YOUR_USDT_BEP20_ADDRESS",
    SOL: "YOUR_USDT_SOL_ADDRESS",
    ARB: "YOUR_USDT_ARB_ADDRESS",
    OP: "YOUR_USDT_OP_ADDRESS",
    TON: "YOUR_USDT_TON_ADDRESS",
  },
  USDC: {
    ERC20: "YOUR_USDC_ERC20_ADDRESS",
    BEP20: "YOUR_USDC_BEP20_ADDRESS",
    SOL: "YOUR_USDC_SOL_ADDRESS",
    ARB: "YOUR_USDC_ARB_ADDRESS",
  },
  BNB: { BEP20: "YOUR_BNB_BEP20_ADDRESS" },
  SOL: { SOL: "YOUR_SOL_ADDRESS" },
  XRP: { XRP: "YOUR_XRP_ADDRESS" },
  ADA: { ADA: "YOUR_ADA_ADDRESS" },
  DOGE: { DOGE: "YOUR_DOGE_ADDRESS" },
  TRX: { TRC20: "YOUR_TRX_ADDRESS" },
  TON: { TON: "YOUR_TON_ADDRESS" },
  MATIC: { MATIC: "YOUR_MATIC_ADDRESS", ERC20: "YOUR_MATIC_ERC20_ADDRESS" },
  LTC: { LTC: "YOUR_LTC_ADDRESS" },
  AVAX: { "AVAX-C": "YOUR_AVAX_ADDRESS", BEP20: "YOUR_AVAX_BEP20_ADDRESS" },
  DOT: { DOT: "YOUR_DOT_ADDRESS" },
  LINK: { ERC20: "YOUR_LINK_ERC20_ADDRESS", BEP20: "YOUR_LINK_BEP20_ADDRESS" },
  ATOM: { ATOM: "YOUR_ATOM_ADDRESS" },
  UNI: { ERC20: "YOUR_UNI_ADDRESS" },
  XLM: { XLM: "YOUR_XLM_ADDRESS" },
  BCH: { BCH: "YOUR_BCH_ADDRESS" },
  ETC: { ETC: "YOUR_ETC_ADDRESS" },
  FIL: { FIL: "YOUR_FIL_ADDRESS" },
  APT: { APT: "YOUR_APT_ADDRESS" },
  ARB: { ARB: "YOUR_ARB_ADDRESS" },
  OP: { OP: "YOUR_OP_ADDRESS" },
  NEAR: { NEAR: "YOUR_NEAR_ADDRESS" },
  INJ: { INJ: "YOUR_INJ_ADDRESS" },
  SUI: { SUI: "YOUR_SUI_ADDRESS" },
  SEI: { SEI: "YOUR_SEI_ADDRESS" },
  FTM: { FTM: "YOUR_FTM_ADDRESS" },
  ALGO: { ALGO: "YOUR_ALGO_ADDRESS" },
  HBAR: { HBAR: "YOUR_HBAR_ADDRESS" },
  VET: { VET: "YOUR_VET_ADDRESS" },
  EGLD: { EGLD: "YOUR_EGLD_ADDRESS" },
  XMR: { XMR: "YOUR_XMR_ADDRESS" },
};
